### ISSUE TITLE
Does not accept null value

### ISSUE THREAD

**Issue by SnipedCode** [VFPX/nfJson#1]
Hello,

I'm getting a error when I try to convert my JSON back to a cursor.

USE MYTABLE1
lcJSON = nfcursortojson4vfp()
= nfjsontocursor(lcJSON,"MYTABLE2")

On a field type DATETIME, I get error : **Does not accept null value**

in last lines 
"Insert Into (cName) From Name oRow"

any workaround ?

**Comment by mplazac** [comment]
Make sure you create the table allowing null values before converting to Json. 
and lcJson is not modified after nfCursorToJson4Vfp().

The following code works fine:

```
clear
close tables all
create cursor temp ( test i null , today t null )
insert into temp ( test, today ) values ( .null.,.null. )

tempAsJson = nfCursorToJson4vfp()
nfJsonToCursor( m.tempAsJson ,'mycopy')

?  mycopy.test, mycopy.today
```

If you continue experimenting the problem please post a code snippet to reproduce it.

**Comment by SnipedCode** [comment]
Is it possible to modify the nfJsonToCursor function to prevent the .null. value and replace it with empty value instead so the error will not occur in the SQL insert?

Because the way you describe, I have to make a cursor and define all the fields before using the function. 
Some of my table have over 200 fields and I can't define all of then with a null parameters.

Can you indicate me where this null value is assigned so I can modify the function?

**Comment by SnipedCode** [comment]
is this give you an error or it's my foxpro setting ?

CREATE CURSOR test(test T)
APPEND BLANK
browse && no null value here!

tempAsJson = nfCursorToJson4vfp()
nfJsonToCursor( m.tempAsJson ,'mycopy') &&Does not accept null value !
RETURN

**Comment by SnipedCode** [comment]
OK PROBLEM SOLVED ! :)

in the program **nfjsonread**
there is a function called **jsondatetodt**
in this program, the IIF statment is reversed.... I fixed it and now it work like a charm !!

WOW  :)

here is my 1 line change :


```
*---------------------------------------------------
procedure jsondatetodt( cjsondate , allowEmpty )
*---------------------------------------------------
if m.cJsonDate = '0000-00-00T00:00:00'
*	return iif(m.allowEmpty,{},.null.)
	return iif(m.allowEmpty,.null.,{})    && FIXED !!!!!!!   <-----------<<<<<
else
	return evl(eval('{^'+m.cjsondate+'}'),m.cjsondate)
endif
```

**Comment by SnipedCode** [comment]
I decide to change it this way because Im not sure if you pass 2 parameters somewhere
Let me know what you think.

Thanks

```
*---------------------------------------------------
procedure jsondatetodt( cjsondate , allowEmpty )
*---------------------------------------------------
IF PARAMETERS() = 1
	m.allowEmpty = .T.  && true by default 
ENDIF 
if m.cJsonDate = '0000-00-00T00:00:00'
	return iif(m.allowEmpty,{},.null.)
else
	return evl(eval('{^'+m.cjsondate+'}'),m.cjsondate)
endif

```

**Comment by mplazac** [comment]
Ok the problem here was that MYTABLE1 did not had null values, but empty dates, wich are not allowed on any other product except vfp, and nfJsonRead convert them to .null. as expected... 

It's great you found that nfJsonRead had that case already solved -but It was unimplemented!. 

I'll update the library with the 3rd parameter enabled:

 nfJsonRead( cjsonstr,revivecollection,allowEmptyDates)

Thanks for your collaboration.

**Comment by mplazac** [comment]
Ok the problem here was that MYTABLE1 did not had null values, but empty dates, wich are not allowed on any other product except vfp, and nfJsonRead convert them to .null. as expected... 

It's great you found that nfJsonRead had that case already solved -but It was unimplemented!. 

I'll update the library with the 3rd parameter enabled:

 nfJsonRead( cjsonstr,revivecollection,allowEmptyDates)

Thanks for your collaboration.

**Comment by mplazac** [comment]
I just Updated the library and decided it was not appropiate to add a 3rd option to allow/not allow empty dates, since what we expect is a unmodified representation of the original, so it behaves like setting allowEmpty = .t. - like you already did - and added other pending changes as follow:

2017/08/05

* no matter wich strictdate you have set, a JsonDateTime "0000-00-00T00:00:00" will return an empty date.
* valid JsonDates with time "T00:00:00" will return a date value ( ie: {"testDate":"2017-12-01T00:00:00"} )
* invalid dates ( ie 2017/50/50 ) properly formatted as Json Date ( ie: 2017-50-50T00:00:00 ) will throw error; 
 ( previous behavior was to return .null. )

Please check tests\emptyDateTest.prg.

**Comment by SnipedCode** [comment]
Working good.
Many thanks for sharing your great programs.
It is very helpful and save me a lot of time.
Continue your great work. 👍

**Comment by mplazac** [comment]
&#129418; = &#128267;
