### ISSUE TITLE
Variable '    ' is not found - runtime environment

### ISSUE THREAD

**Issue by Sn19-20** [VFPX/nfJson#15]
Cause of problem is VFP9r.dll and VFP9RENU.Dll . As I run in exe , these dll comes in picture and cause problem.

**Comment by nfoxdev** [comment]
Please provide detailed error information with data and runtime scenario.

**Comment by Sn19-20** [comment]
In the ZIP file I have attached  
[b2bjson.zip](https://github.com/VFPX/nfJson/files/9351728/b2bjson.zip)

Run the xb.exe and error will come. On deleting VFP9r.dll and VFP9RENU.DLL , error will go

**Comment by nfoxdev** [comment]
The dll versions you are shipping  ( vfp9r.dll  + vfp9renu.dll  9.0.0.2412 ) are for sure older than the vfp9.exe you used to compile your exe. Just make sure your dlls and vfp9.exe versions match. Using the latest ones I attached on zip  ( vfp9r.dll 9.0.0.74.23 + vfp9renu.dll 9.0.0.5815  ) it all runs fine.

[matchver.zip](https://github.com/VFPX/nfJson/files/9353802/matchver.zip)

**Comment by nfoxdev** [comment]
The versions you are shipping are older

**Comment by Sn19-20** [comment]
Grateful Marco... It worked. Thanks a lot once again for wonderful product and your valuable help.

**Comment by cwollenhaupt** [comment]
Because I got caught by this error, as well... This code reproduces the error
```
	Local lcJson
	Text to m.lcJson NoShow PRETEXT 2
		{"a_a":[{"array_b":[{"value":"abc"}]}],"address":{"propA":"12345678901234567890123123456789012345689012345678901234567890123456789"}}
	EndText
	Text to m.lcJson NoShow PRETEXT 2
		{"a_a":[{"array_b":[{"value":"abc"}]}],"address":{"propA":"12345678901234567890123123456789012345689012345678901234567890123456789"}}
	EndText
	*
	Local loObject, lcResult, lcExpected
	loObject = nfJsonRead (m.lcJson)
	lcResult = nfJsonCreate (m.loObject)
```
The error only occurs if there are two nested arrays and the JSON string is longer than 132 characters. The problem is that the return variable in `procobject` (`este`) has the same name as the one the string is added to and the string optimization kicks in (`este = m.este+procobject()`). 

The error disappears when the string is small enough to not trigger any optimization or when string optimization is disabled by replacing `m.este` with `""+m.este`.

The error only happens in VFP 9 without any service pack.

**Comment by nfoxdev** [comment]
I've just checked, and as you mentioned, it's a VFP bug present in the initial release; using an intermediate result resolves it:
```
thisChunk = +[{]+procobject(m.elem ,.f.,m.nonullarrayitem,m.amembersFlag)+[}]
este =  m.este+m.thisChunk
```
thanks!
